### PR TITLE
do not hard-code perl path to /usr/bin

### PR DESCRIPTION
**Pull request by kazuho**
Does same thing as https://github.com/h2o/h2o/commit/9e1ce96cdf199e6d2bf85094f526b7ef6047fe51, fixes https://github.com/h2o/h2o/issues/288.

### CODE REVIEW

**Comment by miyagawa** [comment]
Actually, if you leave out your shebang as either `#!perl` or `#!/usr/bin/perl` (no space after !), ExtUtils::MakeMaker takes care out rewriting it to the perl you're using, when installing the file to $PATH.

```
> head ~/.plenv/versions/5.20.1/bin/carmel
#!/Users/miyagawa/.plenv/versions/5.20.1/bin/perl5.20.1
use strict;

# fastboot
if ($ARGV[0] eq 'exec') {
    require Carmel::Runner;
    exit Carmel::Runner->new->execute(@ARGV[1..$#ARGV]);
}
```

**Comment by miyagawa** [comment]
I see the original bug https://github.com/h2o/h2o/issues/288 and this is a bundle issue. I suggest to provide two executables, one that uses `#!perl` for CPAN installation, and the other with `#!/usr/bin/env perl` that uses whatever user env.

I do the same thing with `cpanm` and I've wished MakeMaker rewrites `#!/usr/bin/env perl` but it actually doesn't.

**Comment by kazuho** [comment]
@miyagawa Thank you for the suggestion.

IMO the ideal fix for the issue would be the one proposed by @shoichikaji on https://github.com/shoichikaji/App-FatPacker-Simple/pull/3#issuecomment-94251094.  For H2O I will create a PR of App::FatPacker-Simple or use an external script to rewrite the shebang.

**Comment by miyagawa** [comment]
Oh that sounds ideal to me!

**Pull request merged**
