### PR TITLE
fixes issue #34: socket file shouldn't be removed when it daemonises

### PR DESCRIPTION
**Pull request by andyjones**
For issue #34, create the scope guard that removes socket files after Server::Starter daemonises otherwise they are removed when the original process exits

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  I haven't run it myself but the test seems fine.

OTOH regarding how we fix the issue, could you please create a `dismiss` method (that works like `Scope::Guard::dismiss`) and call the method in the parent processes that exit during daemonization instead of delaying the instantiation of the guard object?

It is essential to create the object before the files listed in `@paths` are created, to ensure that the files will be removed regardless of why the script terminates.

**Comment by andyjones** [comment]
Sure, I've put it back. For my own learning, do you have anything against Scope::Guard (or Guard) or are you avoiding them to keep the number of dependencies down?

Thanks for this

**Comment by kazuho** [comment]
@andyjones Thank you for the changes.  Merged to master.

I have nothing against Scope::Guard - I pretty much like it.  The only reason it is not used in Server::Starter is to reduce the number of dependencies.

**Comment by kazuho** [comment]
FYI released 0.31 with the fix.

**Comment by andyjones** [comment]
awesome, thank you

**Pull request merged**
